//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "clock_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub message_id: String,
    #[sea_orm(column_type = "Text")]
    pub node_id: String,
    pub clock: Json,
    pub event_count: i32,
    pub is_zk: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub from_addr: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub to_addr: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub signature: String,
    pub raw_message: Option<String>,
    pub create_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
