//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::clock_message::Entity as ClockMessage;
pub use super::merge_log::Entity as MergeLog;
pub use super::node_info::Entity as NodeInfo;
